spring.application.name=backend
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
logging.level.org.springframework=INFO
logging.level.com.project=DEBUG
logging.file.name=logs/app.log
# Properties to initialize database schema and data
spring.datasource.schema=classpath:schema.sql
#spring.datasource.data=classpath:data.sql
spring.jpa.hibernate.ddl-auto=create
spring.sql.init.mode=always

management.endpoint.health.show-details=always
management.health.db.enabled=true